2020-03-03 23:46:05,895 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:46:05,896 DEBUG Using selector: EpollSelector
2020-03-03 23:46:06,367 DEBUG test
2020-03-03 23:51:42,385 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:51:42,386 DEBUG Using selector: EpollSelector
2020-03-03 23:51:42,833 DEBUG test
2020-03-03 23:51:50,424 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:51:50,425 DEBUG Using selector: EpollSelector
2020-03-03 23:51:50,855 DEBUG test
2020-03-03 23:52:06,925 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:52:06,926 DEBUG Using selector: EpollSelector
2020-03-03 23:52:07,361 DEBUG test
2020-03-03 23:52:13,677 DEBUG Using selector: EpollSelector
2020-03-03 23:52:15,941 DEBUG test
2020-03-03 23:52:19,249 WARNING Forbidden (CSRF cookie not set.): /register/
2020-03-03 23:53:04,916 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:53:04,916 DEBUG Using selector: EpollSelector
2020-03-03 23:53:05,341 DEBUG test
2020-03-03 23:54:03,766 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:54:03,767 DEBUG Using selector: EpollSelector
2020-03-03 23:54:08,989 DEBUG test
2020-03-03 23:55:17,424 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:55:17,425 DEBUG Using selector: EpollSelector
2020-03-03 23:55:21,235 DEBUG test
2020-03-03 23:55:21,235 DEBUG test1
2020-03-03 23:56:26,048 DEBUG test
2020-03-03 23:56:26,048 DEBUG test1
2020-03-03 23:56:26,051 DEBUG test2
2020-03-03 23:56:26,098 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 19, in register
    user = serializer.create(serializer.validated_data, commit=False)
TypeError: create() got an unexpected keyword argument 'commit'
2020-03-03 23:57:37,819 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-03 23:57:37,820 DEBUG Using selector: EpollSelector
2020-03-03 23:58:14,898 DEBUG test
2020-03-03 23:58:14,898 DEBUG test1
2020-03-03 23:58:14,902 DEBUG test2
2020-03-03 23:58:14,904 DEBUG *****
2020-03-03 23:58:14,904 DEBUG kukla
2020-03-03 23:58:15,063 DEBUG pbkdf2_sha256$180000$anEVrNI68xQL$jq4MCxnf6AimMOkxyh0IxQ8LiR4gH9fqUGT2x6voCRE=
2020-03-04 00:01:10,684 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-04 00:01:10,685 DEBUG Using selector: EpollSelector
2020-03-04 00:02:06,154 DEBUG test
2020-03-04 00:02:06,154 DEBUG test1
2020-03-04 00:03:24,305 DEBUG test
2020-03-04 00:03:24,306 DEBUG test1
2020-03-04 00:03:24,308 DEBUG test2
2020-03-04 00:03:24,340 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 20, in register
    serializer.set_password(password)
AttributeError: 'UserSerializer' object has no attribute 'set_password'
2020-03-04 00:04:19,960 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-04 00:04:19,961 DEBUG Using selector: EpollSelector
2020-03-04 00:04:49,177 DEBUG test
2020-03-04 00:04:49,177 DEBUG test1
2020-03-04 00:05:52,131 DEBUG test
2020-03-04 00:05:52,131 DEBUG test1
2020-03-04 00:05:52,134 DEBUG test2
2020-03-04 00:05:52,139 DEBUG *****
2020-03-04 00:05:52,139 DEBUG jukla
2020-03-04 00:05:52,302 DEBUG pbkdf2_sha256$180000$TcDD9UQOm2Ce$Ha812M8WprcNLSfHIa2+KPQ0uf20FPax1h2CHrEXTM8=
2020-03-04 00:23:51,606 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-04 00:23:51,606 DEBUG Using selector: EpollSelector
2020-03-04 00:25:33,525 DEBUG test
2020-03-04 00:25:33,525 DEBUG test1
2020-03-04 00:25:33,528 DEBUG test2
2020-03-04 00:25:33,702 DEBUG *****
2020-03-04 00:25:33,702 DEBUG qukla
2020-03-04 00:25:33,702 DEBUG pbkdf2_sha256$180000$LDddSOQl4KSm$lQCFMr7StMzbzG8PRFruG17PGUTG25qCoS2z6utkMI8=
2020-03-07 22:25:59,313 DEBUG test
2020-03-07 22:25:59,313 DEBUG test1
2020-03-07 22:25:59,314 DEBUG <class 'dict'>
2020-03-07 22:25:59,314 DEBUG {'username': 'qukla', 'password': 'poklop'}
2020-03-07 22:25:59,315 DEBUG test2
2020-03-07 22:25:59,348 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 23, in register
    user = User(username=serializer.validated_data['email'], email=serializer.validated_data['email'])
KeyError: 'email'
2020-03-07 22:26:15,571 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-07 22:26:15,572 DEBUG Using selector: EpollSelector
2020-03-07 22:32:39,653 DEBUG test
2020-03-07 22:32:39,653 DEBUG test1
2020-03-07 22:32:39,653 DEBUG <class 'dict'>
2020-03-07 22:32:39,653 DEBUG {'email': 's.dmitrievlol@yandex.ru', 'password': 'poklop17'}
2020-03-07 22:32:39,658 DEBUG test2
2020-03-07 22:33:16,740 DEBUG Using selector: EpollSelector
2020-03-07 22:37:44,264 DEBUG test
2020-03-07 22:37:44,264 DEBUG test1
2020-03-07 22:37:44,265 DEBUG <class 'dict'>
2020-03-07 22:37:44,265 DEBUG {'email': 's.dmitrievlol@yandex.ru', 'password': 'poklop17'}
2020-03-07 22:37:44,268 DEBUG test2
2020-03-07 22:37:44,465 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 's.dmitrievlol@yandex.ru' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 25, in register
    user.save()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1384, in execute_sql
    cursor.execute(sql, params)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 's.dmitrievlol@yandex.ru' for key 'username'")
2020-03-07 22:40:08,177 INFO /home/perespimka/monyze/monyzeapp/serializers.py changed, reloading.
2020-03-07 22:40:08,178 DEBUG Using selector: EpollSelector
2020-03-07 23:05:18,943 DEBUG test
2020-03-07 23:05:18,943 DEBUG test1
2020-03-07 23:06:15,432 DEBUG test
2020-03-07 23:06:15,432 DEBUG test1
2020-03-07 23:06:15,438 DEBUG test2
2020-03-07 23:06:15,719 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 33, in register
    profile_tgcode_save(user)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 14, in profile_tgcode_save
    profile.tg_code = hashlib.md5(user.username + user.password)
TypeError: Unicode-objects must be encoded before hashing
2020-03-07 23:07:54,499 DEBUG Using selector: EpollSelector
2020-03-07 23:14:25,900 DEBUG test
2020-03-07 23:14:25,900 DEBUG test1
2020-03-07 23:15:11,883 DEBUG test
2020-03-07 23:15:11,883 DEBUG test1
2020-03-07 23:15:11,888 DEBUG test2
2020-03-07 23:15:12,128 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 33, in register
    profile_tgcode_save(user)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 14, in profile_tgcode_save
    profile.tg_code = hashlib.md5(str(user.username) + str(user.password))
TypeError: Unicode-objects must be encoded before hashing
2020-03-07 23:17:27,047 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-07 23:17:27,048 DEBUG Using selector: EpollSelector
2020-03-07 23:18:09,260 DEBUG test
2020-03-07 23:18:09,260 DEBUG test1
2020-03-07 23:18:09,266 DEBUG test2
2020-03-07 23:18:09,464 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 33, in register
    profile_tgcode_save(user)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 14, in profile_tgcode_save
    profile.tg_code = hashlib.md5(str(user.username.encode('utf-8')) + str(user.password.encode('utf-8')))
TypeError: Unicode-objects must be encoded before hashing
2020-03-07 23:21:46,647 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-07 23:21:46,648 DEBUG Using selector: EpollSelector
2020-03-07 23:22:23,178 DEBUG test
2020-03-07 23:22:23,178 DEBUG test1
2020-03-07 23:22:23,184 DEBUG test2
2020-03-07 23:31:00,713 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-07 23:31:00,714 DEBUG Using selector: EpollSelector
2020-03-07 23:31:36,922 DEBUG test
2020-03-07 23:31:36,922 DEBUG test1
2020-03-07 23:31:36,927 DEBUG test2
2020-03-07 23:32:48,288 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-07 23:32:48,289 DEBUG Using selector: EpollSelector
2020-03-10 20:26:48,619 DEBUG test
2020-03-10 20:26:48,683 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 26, in register
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2020-03-10 21:10:31,119 INFO /home/perespimka/monyze/monyze/settings.py changed, reloading.
2020-03-10 21:10:31,120 DEBUG Using selector: EpollSelector
2020-03-10 21:11:15,511 DEBUG test
2020-03-10 21:11:16,837 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 26, in register
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 700, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2020-03-10 21:12:39,307 INFO /home/perespimka/monyze/monyze/settings.py changed, reloading.
2020-03-10 21:12:39,307 DEBUG Using selector: EpollSelector
2020-03-10 21:12:48,409 DEBUG test
2020-03-10 21:12:52,277 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/monyzeapp/views.py", line 26, in register
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'s.dmitrievlol@yandex.ru': (504, b'5.5.2 <Serg>: Sender address rejected: need fully-qualified address')}
2020-03-10 21:15:27,694 INFO /home/perespimka/monyze/monyze/settings.py changed, reloading.
2020-03-10 21:15:27,695 DEBUG Using selector: EpollSelector
2020-03-10 21:15:40,470 DEBUG test
2020-03-10 21:15:42,710 DEBUG test1
2020-03-10 21:15:42,719 WARNING Bad Request: /register/
2020-03-10 21:18:43,184 DEBUG Using selector: EpollSelector
2020-03-10 23:18:15,597 DEBUG test
2020-03-10 23:18:15,597 DEBUG test1
2020-03-10 23:18:15,601 WARNING Bad Request: /register/
2020-03-10 23:18:32,517 INFO /home/perespimka/monyze/monyzeapp/views.py changed, reloading.
2020-03-10 23:18:32,518 DEBUG Using selector: EpollSelector
2020-03-10 23:19:05,494 DEBUG test
2020-03-10 23:19:05,494 DEBUG test1
2020-03-10 23:19:05,499 DEBUG test2
2020-03-10 23:19:33,840 INFO /home/perespimka/monyze/monyzeapp/serializers.py changed, reloading.
2020-03-10 23:19:33,841 DEBUG Using selector: EpollSelector
2020-04-30 16:01:17,802 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2020-04-30 16:01:17,902 WARNING Bad Request: /amoapi/mail_to_lab/
2020-04-30 16:01:55,997 DEBUG Using selector: EpollSelector
2020-04-30 16:03:29,579 WARNING Not Found: /amoapi/mail_to_lab/
2020-04-30 16:04:15,564 INFO /home/perespimka/monyze/amoapi/urls.py changed, reloading.
2020-04-30 16:04:15,564 DEBUG Using selector: EpollSelector
2020-04-30 16:05:27,634 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 16:05:27,635 DEBUG Using selector: EpollSelector
2020-04-30 16:06:17,244 INFO /home/perespimka/monyze/amoapi/urls.py changed, reloading.
2020-04-30 16:06:17,245 DEBUG Using selector: EpollSelector
2020-04-30 16:06:29,620 INFO /home/perespimka/monyze/amoapi/urls.py changed, reloading.
2020-04-30 16:06:29,621 DEBUG Using selector: EpollSelector
2020-04-30 16:06:35,561 INFO /home/perespimka/monyze/amoapi/urls.py changed, reloading.
2020-04-30 16:06:35,562 DEBUG Using selector: EpollSelector
2020-04-30 16:06:43,229 ERROR Internal Server Error: /amoapi/mail_to_lab/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 11, in mail_to_lab
    logging.debug(request.data)
AttributeError: 'WSGIRequest' object has no attribute 'data'
2020-04-30 16:06:48,143 DEBUG Using selector: EpollSelector
2020-04-30 16:07:18,154 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 16:07:18,155 DEBUG Using selector: EpollSelector
2020-04-30 16:07:23,032 DEBUG Using selector: EpollSelector
2020-04-30 16:07:29,062 DEBUG <WSGIRequest: GET '/amoapi/mail_to_lab/'>
2020-04-30 16:09:06,826 DEBUG Using selector: EpollSelector
2020-04-30 16:20:21,728 DEBUG request:
2020-04-30 16:20:21,729 DEBUG <WSGIRequest: GET '/amoapi/mail_to_lab/'>
2020-04-30 16:41:23,974 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 16:41:23,975 DEBUG Using selector: EpollSelector
2020-04-30 16:57:26,183 WARNING Forbidden (CSRF cookie not set.): /amoapi/mail_to_lab/
2020-04-30 16:58:30,405 WARNING Forbidden (CSRF cookie not set.): /amoapi/mail_to_lab/
2020-04-30 16:58:47,069 DEBUG Using selector: EpollSelector
2020-04-30 16:59:37,550 DEBUG Using selector: EpollSelector
2020-04-30 17:00:16,429 DEBUG request:
2020-04-30 17:00:16,429 DEBUG <rest_framework.request.Request object at 0x7f8a34236370>
2020-04-30 17:00:50,103 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 17:00:50,104 DEBUG Using selector: EpollSelector
2020-04-30 17:00:53,925 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 17:00:53,926 DEBUG Using selector: EpollSelector
2020-04-30 17:01:01,429 DEBUG Using selector: EpollSelector
2020-04-30 17:01:16,324 DEBUG request:
2020-04-30 17:01:16,324 DEBUG <QueryDict: {'leads[status][0][id]': ['6208283'], 'leads[status][0][status_id]': ['32037649'], 'leads[status][0][pipeline_id]': ['3127180'], 'leads[status][0][old_status_id]': ['32037652'], 'leads[status][0][old_pipeline_id]': ['3127180'], 'account[id]': ['28812997'], 'account[subdomain]': ['stardustpaintsamo']}>
2020-04-30 17:19:23,660 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 17:19:23,661 DEBUG Using selector: EpollSelector
2020-04-30 22:14:53,302 DEBUG Using selector: EpollSelector
2020-04-30 22:17:19,295 DEBUG request:
2020-04-30 22:17:19,295 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:17:19,337 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 30, in send_email
    sample_data_to_xlsx(request.data['samle_data'])
KeyError: 'samle_data'
2020-04-30 22:17:38,527 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 22:17:38,528 DEBUG Using selector: EpollSelector
2020-04-30 22:17:46,233 DEBUG request:
2020-04-30 22:17:46,233 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:17:46,288 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 30, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 13, in sample_data_to_xlsx
    df_sample_data = pd.DataFrame(sample_data)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
2020-04-30 22:21:10,736 DEBUG Using selector: EpollSelector
2020-04-30 22:21:16,604 DEBUG request:
2020-04-30 22:21:16,605 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': ['testval1'], 'testkey2': [2]}}
2020-04-30 22:21:16,679 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 30, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 15, in sample_data_to_xlsx
    df_sample_data.to_excel(fname, index=None)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 2175, in to_excel
    formatter.write(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 726, in write
    writer = ExcelWriter(stringify_path(writer), engine=engine)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 18, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
2020-04-30 22:21:47,829 DEBUG Using selector: EpollSelector
2020-04-30 22:22:12,421 DEBUG request:
2020-04-30 22:22:12,421 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': ['testval1'], 'testkey2': [2]}}
2020-04-30 22:22:19,629 DEBUG Using selector: EpollSelector
2020-04-30 22:31:13,575 DEBUG request:
2020-04-30 22:31:13,575 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:31:19,265 DEBUG Using selector: EpollSelector
2020-04-30 22:55:19,390 DEBUG request:
2020-04-30 22:55:19,391 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:55:19,613 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 41, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 23, in sample_data_to_xlsx
    df_sample_data.to_excel(fname, index=None)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 2175, in to_excel
    formatter.write(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 738, in write
    writer.save()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 43, in save
    return self.book.save(self.path)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 392, in save
    save_workbook(self, filename)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'mail_files/1588276519394.xlsx'
2020-04-30 22:56:59,578 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 22:56:59,579 DEBUG Using selector: EpollSelector
2020-04-30 22:57:03,797 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 22:57:03,798 DEBUG Using selector: EpollSelector
2020-04-30 22:57:05,899 DEBUG Using selector: EpollSelector
2020-04-30 22:57:15,670 DEBUG request:
2020-04-30 22:57:15,670 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:57:15,712 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 41, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 22, in sample_data_to_xlsx
    fname = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/mail_files/' + str_time
NameError: name 'os' is not defined
2020-04-30 22:57:22,329 DEBUG request:
2020-04-30 22:57:22,330 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:57:22,348 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 41, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 22, in sample_data_to_xlsx
    fname = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/mail_files/' + str_time
NameError: name 'os' is not defined
2020-04-30 22:57:49,671 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 22:57:49,672 DEBUG Using selector: EpollSelector
2020-04-30 22:58:00,203 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 22:58:00,204 DEBUG Using selector: EpollSelector
2020-04-30 22:58:03,164 DEBUG Using selector: EpollSelector
2020-04-30 22:58:10,318 DEBUG request:
2020-04-30 22:58:10,319 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:58:10,522 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 42, in send_email
    sample_data_to_xlsx(request.data['sample_data'])
  File "/home/perespimka/monyze/amoapi/views.py", line 24, in sample_data_to_xlsx
    df_sample_data.to_excel(fname, index=None)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 2175, in to_excel
    formatter.write(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 738, in write
    writer.save()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 43, in save
    return self.book.save(self.path)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 392, in save
    save_workbook(self, filename)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/openpyxl/writer/excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/perespimka/monyze/mail_files/1588276690320.xlsx'
2020-04-30 22:58:30,765 DEBUG Using selector: EpollSelector
2020-04-30 22:59:40,860 DEBUG request:
2020-04-30 22:59:40,861 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}}
2020-04-30 22:59:52,453 DEBUG Using selector: EpollSelector
2020-04-30 23:52:56,046 DEBUG request:
2020-04-30 23:52:56,046 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'piska@stardustpaints.ru'}
2020-04-30 23:52:56,244 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 51, in send_email
    send_mail_to_lab(request.data)
  File "/home/perespimka/monyze/amoapi/views.py", line 41, in send_mail_to_lab
    em.attach_file(attach)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 322, in attach_file
    with path.open('rb') as file:
  File "/usr/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '1588279976047.xlsx'
2020-04-30 23:53:43,420 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 23:53:43,420 DEBUG Using selector: EpollSelector
2020-04-30 23:53:53,120 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 23:53:53,121 DEBUG Using selector: EpollSelector
2020-04-30 23:54:49,430 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 23:54:49,431 DEBUG Using selector: EpollSelector
2020-04-30 23:54:57,995 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-04-30 23:54:57,996 DEBUG Using selector: EpollSelector
2020-04-30 23:54:59,743 DEBUG Using selector: EpollSelector
2020-04-30 23:55:08,576 DEBUG request:
2020-04-30 23:55:08,577 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'piska@stardustpaints.ru'}
2020-04-30 23:55:10,649 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 49, in send_email
    send_mail_to_lab(request.data)
  File "/home/perespimka/monyze/amoapi/views.py", line 40, in send_mail_to_lab
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'s.dmitrievlol@yandex.ru': (550, b'5.1.0 <piska@stardustpaints.ru>: Sender address rejected: User unknown in virtual mailbox table')}
2020-04-30 23:56:41,532 DEBUG request:
2020-04-30 23:56:41,533 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'sa@stardustpaints.ru'}
2020-04-30 23:56:43,283 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 49, in send_email
    send_mail_to_lab(request.data)
  File "/home/perespimka/monyze/amoapi/views.py", line 40, in send_mail_to_lab
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'s.dmitrievlol@yandex.ru': (553, b'5.7.1 <sa@stardustpaints.ru>: Sender address rejected: not owned by user dmitrievs@stardustpaints.ru')}
2020-04-30 23:57:45,075 DEBUG request:
2020-04-30 23:57:45,076 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'dmitrievs@stardustpaints.ru'}
2020-05-01 00:01:46,032 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 00:01:46,033 DEBUG Using selector: EpollSelector
2020-05-01 00:02:15,861 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 00:02:15,862 DEBUG Using selector: EpollSelector
2020-05-01 00:02:19,364 DEBUG Using selector: EpollSelector
2020-05-01 00:02:27,398 DEBUG request:
2020-05-01 00:02:27,398 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'dmitrievs@stardustpaints.ru'}
2020-05-01 00:02:58,943 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 00:02:58,944 DEBUG Using selector: EpollSelector
2020-05-01 00:04:45,807 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 00:04:45,808 DEBUG Using selector: EpollSelector
2020-05-01 00:31:45,179 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 00:31:45,180 DEBUG Using selector: EpollSelector
2020-05-01 12:13:11,686 DEBUG request:
2020-05-01 12:13:11,687 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'soloviev@stardustpaints.ru'}
2020-05-01 12:13:15,733 ERROR Internal Server Error: /amoapi/send_email/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 80, in send_email
    send_mail_to_lab(request.data)
  File "/home/perespimka/monyze/amoapi/views.py", line 71, in send_mail_to_lab
    em.send()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'s.dmitrievlol@yandex.ru': (553, b'5.7.1 <soloviev@stardustpaints.ru>: Sender address rejected: not owned by user dmitrievs@stardustpaints.ru')}
2020-05-01 12:16:36,204 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:16:36,205 DEBUG Using selector: EpollSelector
2020-05-01 12:16:57,576 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:16:57,576 DEBUG Using selector: EpollSelector
2020-05-01 12:19:12,709 DEBUG Using selector: EpollSelector
2020-05-01 12:35:22,707 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:35:22,708 DEBUG Using selector: EpollSelector
2020-05-01 12:37:08,274 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:37:08,275 DEBUG Using selector: EpollSelector
2020-05-01 12:37:26,512 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:37:26,513 DEBUG Using selector: EpollSelector
2020-05-01 12:37:35,053 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:37:35,054 DEBUG Using selector: EpollSelector
2020-05-01 12:38:03,883 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:38:03,884 DEBUG Using selector: EpollSelector
2020-05-01 12:38:09,930 DEBUG request:
2020-05-01 12:38:09,930 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 12:38:59,560 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:38:59,561 DEBUG Using selector: EpollSelector
2020-05-01 12:39:11,257 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 12:39:11,258 DEBUG Using selector: EpollSelector
2020-05-01 12:40:39,867 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.stardustpaints.ru/amoapi/send_email/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2020-05-01 13:00:28,874 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 13:00:28,874 DEBUG Using selector: EpollSelector
2020-05-01 13:00:56,867 INFO /home/perespimka/monyze/amoapi/views.py changed, reloading.
2020-05-01 13:00:56,868 DEBUG Using selector: EpollSelector
2020-05-01 13:02:38,000 DEBUG request:
2020-05-01 13:02:38,000 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 13:29:39,133 DEBUG Using selector: EpollSelector
2020-05-01 14:06:30,493 DEBUG request:
2020-05-01 14:06:30,493 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:11:56,201 DEBUG request:
2020-05-01 14:11:56,202 DEBUG {'state': 'send_lab', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:12:57,567 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.stardustpaints.ru/amoapi/send_email/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2020-05-01 14:14:51,570 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.stardustpaints.ru/amoapi/send_email/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2020-05-01 14:17:01,811 DEBUG request:
2020-05-01 14:17:01,812 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:25:25,202 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.stardustpaints.ru/amoapi/send_email/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2020-05-01 14:27:24,064 WARNING Not Found: /amoapi/send_email
2020-05-01 14:28:51,593 WARNING Not Found: /amoapi/send_email
2020-05-01 14:29:11,323 DEBUG request:
2020-05-01 14:29:11,324 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:30:37,756 WARNING Not Found: /amoapi/send_email
2020-05-01 14:31:30,633 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.stardustpaints.ru/amoapi/send_email/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2020-05-01 14:33:15,552 WARNING Not Found: /amoapi/send_email
2020-05-01 14:33:22,216 DEBUG request:
2020-05-01 14:33:22,217 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:34:08,240 DEBUG request:
2020-05-01 14:34:08,241 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 14:34:26,344 DEBUG request:
2020-05-01 14:34:26,345 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 14:34:26,385 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 61, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 15:03:11,224 DEBUG request:
2020-05-01 15:03:11,269 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/request.py", line 409, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 60, in send_email
    logging.debug(request.type)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/request.py", line 411, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'type'
2020-05-01 15:03:54,528 DEBUG request:
2020-05-01 15:03:54,529 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 15:04:52,154 DEBUG request:
2020-05-01 15:04:52,154 DEBUG application/json
2020-05-01 15:04:52,154 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 15:05:09,676 DEBUG request:
2020-05-01 15:05:09,677 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 15:05:09,677 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 15:05:09,712 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 15:51:44,090 DEBUG request:
2020-05-01 15:51:44,090 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 15:51:44,091 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 15:51:44,130 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 15:54:19,839 DEBUG request:
2020-05-01 15:54:19,839 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 15:54:19,840 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 15:54:19,857 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 15:57:54,473 DEBUG request:
2020-05-01 15:57:54,473 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 15:57:54,474 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 15:57:54,496 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 15:59:49,365 DEBUG request:
2020-05-01 15:59:49,366 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 15:59:49,366 DEBUG <QueryDict: {'{"state":"send_lab","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"sample","name":"RAL1221-PE-н/о-н/о","product":"Краска","client_sample":"","ntime_applying":"","status":"Не определено","reason":"Не определено","basis":"PE","catalog":"RAL","code":"1221","shine":"Не определено","facture":"Не определено","temperature":"Не определено","postforming":"Нет","applying":"Внутренее","panels":"","powder":"","surface_thin":"","surface_type":[],"comment":"","metallic":0,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 15:59:49,407 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 16:00:04,469 DEBUG request:
2020-05-01 16:00:04,470 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 16:00:04,471 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"a3VrdWhhQG1haWwucnU': ['","manager_mail_pass":"MTIza3VrdWhh","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 16:00:04,505 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 62, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 16:11:52,353 WARNING Method Not Allowed: /amoapi/send_email
2020-05-01 16:15:11,887 DEBUG request:
2020-05-01 16:15:11,888 DEBUG application/json
2020-05-01 16:15:11,888 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 16:20:16,110 DEBUG request:
2020-05-01 16:20:16,110 DEBUG application/json
2020-05-01 16:20:16,110 DEBUG {'state': 'send_prod', 'manager_mail': 'a3VrdWhhQG1haWwucnU=', 'manager_mail_pass': 'MTIza3VrdWhh', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-PE-80/100%-ант', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '5', 'kp_price': '5', 'vol': '3', 'price': '4', 'basis': 'PE', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Антик', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-01 16:20:24,724 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 63, in send_email
    send_mail_to_lab(request.data)
  File "/home/perespimka/monyze/amoapi/views.py", line 44, in send_mail_to_lab
    EmailBackend(
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: UGFzc3dvcmQ6')
2020-05-01 16:31:41,054 DEBUG request:
2020-05-01 16:31:41,054 DEBUG application/json
2020-05-01 16:31:41,055 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-PE-80/100%-ант', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '5', 'kp_price': '5', 'vol': '3', 'price': '4', 'basis': 'PE', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Антик', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-01 16:31:41,055 DEBUG ************************
2020-05-01 16:31:41,055 DEBUG soloviev@stardustpaints.ru
2020-05-01 16:31:41,055 DEBUG 33Kgtsl11
2020-05-01 16:31:41,055 DEBUG ************************
2020-05-01 16:56:36,244 DEBUG request:
2020-05-01 16:56:36,244 DEBUG application/json
2020-05-01 16:56:36,245 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 16:56:36,245 DEBUG ************************
2020-05-01 16:56:36,245 DEBUG soloviev@stardustpaints.ru
2020-05-01 16:56:36,245 DEBUG 33Kgtsl11
2020-05-01 16:56:36,245 DEBUG ************************
2020-05-01 17:42:49,033 DEBUG request:
2020-05-01 17:42:49,034 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 17:42:49,034 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 17:42:49,081 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 17:43:43,050 DEBUG request:
2020-05-01 17:43:43,050 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 17:43:43,051 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1019-PE-80/100%-шгр","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1019","shine":"Глянцевая 80-100%","facture":"Шагрень","temperature":"Стандарт","postforming":"Нет","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"dsfsd","metallic":1,"chameleon":1,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 17:43:43,097 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 18:24:48,263 ERROR Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
2020-05-01 18:24:48,313 WARNING Bad Request: /amoapi/send_email
2020-05-01 18:26:54,434 ERROR Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
2020-05-01 18:26:54,465 WARNING Bad Request: /amoapi/send_email
2020-05-01 18:29:22,409 DEBUG request:
2020-05-01 18:29:22,409 DEBUG application/json
2020-05-01 18:29:22,409 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-01 18:29:22,409 DEBUG ************************
2020-05-01 18:29:22,410 DEBUG soloviev@stardustpaints.ru
2020-05-01 18:29:22,410 DEBUG 33Kgtsl11
2020-05-01 18:29:22,410 DEBUG ************************
2020-05-01 18:30:56,466 DEBUG request:
2020-05-01 18:30:56,467 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 18:30:56,467 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 18:30:56,513 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 19:11:28,403 DEBUG request:
2020-05-01 19:11:28,403 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 19:11:28,404 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 19:11:28,437 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 20:08:08,201 DEBUG request:
2020-05-01 20:08:08,201 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 20:08:08,201 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 20:08:08,213 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 20:22:18,827 DEBUG request:
2020-05-01 20:22:18,827 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 20:22:18,828 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 20:22:18,861 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 20:23:06,049 DEBUG request:
2020-05-01 20:23:06,049 DEBUG application/json
2020-05-01 20:23:06,050 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-PE-80/100%-ант', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '5', 'kp_price': '5', 'vol': '3', 'price': '4', 'basis': 'PE', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Антик', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-01 20:23:06,050 DEBUG ************************
2020-05-01 20:23:06,050 DEBUG soloviev@stardustpaints.ru
2020-05-01 20:23:06,051 DEBUG 33Kgtsl11
2020-05-01 20:23:06,051 DEBUG ************************
2020-05-01 20:24:44,847 DEBUG request:
2020-05-01 20:24:44,847 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 20:24:44,848 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 20:24:44,863 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 21:16:00,264 DEBUG request:
2020-05-01 21:16:00,264 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 21:16:00,265 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 21:16:00,294 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 21:16:52,504 DEBUG request:
2020-05-01 21:16:52,504 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 21:16:52,505 DEBUG <QueryDict: {'{"state":"send_prod","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"paint","name":"RAL1018-PE-80/100%-ант","product":"Краска","delivery_date":"","delivery_terms":"Не определено","potential_vol":"5","kp_price":"5","vol":"3","price":"4","basis":"PE","catalog":"RAL","code":"1018","shine":"Глянцевая 80-100%","facture":"Антик","temperature":"Стандарт","postforming":"T0","applying":"Внутренее","surface_thin":"","surface_type":[],"comment":"","metallic":1,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 21:16:52,518 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 21:19:43,234 DEBUG request:
2020-05-01 21:19:43,235 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 21:19:43,235 DEBUG <QueryDict: {'{"state":"send_lab","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"sample","name":"RAL2514-PE-н/о-н/о","product":"Краска","client_sample":"","ntime_applying":"","status":"Не определено","reason":"Не определено","basis":"PE","catalog":"RAL","code":"2514","shine":"Не определено","facture":"Не определено","temperature":"Не определено","postforming":"Нет","applying":"Внутренее","panels":"","powder":"","surface_thin":"","surface_type":[],"comment":"","metallic":0,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 21:19:43,267 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 21:29:02,981 DEBUG request:
2020-05-01 21:29:02,981 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 21:29:02,981 DEBUG <QueryDict: {'{"state":"send_lab","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"sample","name":"RAL2514-PE-н/о-н/о","product":"Краска","client_sample":"","ntime_applying":"","status":"Не определено","reason":"Не определено","basis":"PE","catalog":"RAL","code":"2514","shine":"Не определено","facture":"Не определено","temperature":"Не определено","postforming":"Нет","applying":"Внутренее","panels":"","powder":"","surface_thin":"","surface_type":[],"comment":"","metallic":0,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 21:29:02,993 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-01 21:45:26,114 DEBUG request:
2020-05-01 21:45:26,115 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-01 21:45:26,115 DEBUG <QueryDict: {'{"state":"send_lab","manager_mail":"c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU': ['","manager_mail_pass":"MzNLZ3RzbDEx","sample_data":{"product_type":"sample","name":"RAL2514-PE-н/о-н/о","product":"Краска","client_sample":"","ntime_applying":"","status":"Не определено","reason":"Не определено","basis":"PE","catalog":"RAL","code":"2514","shine":"Не определено","facture":"Не определено","temperature":"Не определено","postforming":"Нет","applying":"Внутренее","panels":"","powder":"","surface_thin":"","surface_type":[],"comment":"","metallic":0,"chameleon":0,"antibacterial":0,"antigraffiti":0,"architect":0,"zinc":0}}']}>
2020-05-01 21:45:26,143 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-02 01:49:31,550 DEBUG request:
2020-05-02 01:49:31,550 DEBUG application/json
2020-05-02 01:49:31,550 DEBUG {'state': 'send_prod', 'sample_data': {'testkey1': 'testval1', 'testkey2': 2}, 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx'}
2020-05-02 01:49:31,551 DEBUG ************************
2020-05-02 01:49:31,551 DEBUG soloviev@stardustpaints.ru
2020-05-02 01:49:31,551 DEBUG 33Kgtsl11
2020-05-02 01:49:31,551 DEBUG ************************
2020-05-04 10:26:21,156 DEBUG request:
2020-05-04 10:26:21,156 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-04 10:26:21,157 DEBUG <QueryDict: {'{"bla1":"bla2"}': ['']}>
2020-05-04 10:26:21,213 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-04 10:27:52,157 DEBUG request:
2020-05-04 10:27:52,158 DEBUG application/x-www-form-urlencoded; charset=UTF-8
2020-05-04 10:27:52,159 DEBUG <QueryDict: {'{"bla1":"bla2"}': ['']}>
2020-05-04 10:27:52,190 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'state'
2020-05-04 10:33:06,201 DEBUG request:
2020-05-04 10:33:06,201 DEBUG application/json; charset=UTF-8
2020-05-04 10:33:06,202 DEBUG {'bla1': 'bla2'}
2020-05-04 10:33:06,239 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
KeyError: 'state'
2020-05-04 10:35:46,503 DEBUG request:
2020-05-04 10:35:46,503 DEBUG application/json; charset=UTF-8
2020-05-04 10:35:46,504 DEBUG {'bla1': 'bla2'}
2020-05-04 10:35:46,540 ERROR Internal Server Error: /amoapi/send_email
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 67, in send_email
    if request.data['state'] == 'send_lab' or request.data['state'] == 'send_prod':
KeyError: 'state'
2020-05-04 10:39:22,324 DEBUG request:
2020-05-04 10:39:22,324 DEBUG application/json; charset=UTF-8
2020-05-04 10:39:22,325 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1122-PE-н/о-н/о', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '', 'kp_price': '', 'vol': '', 'price': '', 'basis': 'PE', 'catalog': 'RAL', 'code': '1122', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 10:39:22,325 DEBUG ************************
2020-05-04 10:39:22,325 DEBUG soloviev@stardustpaints.ru
2020-05-04 10:39:22,325 DEBUG 33Kgtsl11
2020-05-04 10:39:22,325 DEBUG ************************
2020-05-04 10:39:59,389 DEBUG request:
2020-05-04 10:39:59,389 DEBUG application/json; charset=UTF-8
2020-05-04 10:39:59,390 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1122-PE-н/о-н/о', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '', 'kp_price': '', 'vol': '', 'price': '', 'basis': 'PE', 'catalog': 'RAL', 'code': '1122', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 10:39:59,390 DEBUG ************************
2020-05-04 10:39:59,390 DEBUG soloviev@stardustpaints.ru
2020-05-04 10:39:59,390 DEBUG 33Kgtsl11
2020-05-04 10:39:59,391 DEBUG ************************
2020-05-04 10:42:03,036 DEBUG request:
2020-05-04 10:42:03,036 DEBUG application/json; charset=UTF-8
2020-05-04 10:42:03,036 DEBUG {'state': 'set_score', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1122-PE-н/о-н/о', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '', 'kp_price': '', 'vol': '', 'price': '', 'basis': 'PE', 'catalog': 'RAL', 'code': '1122', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 10:42:33,101 DEBUG request:
2020-05-04 10:42:33,101 DEBUG application/json; charset=UTF-8
2020-05-04 10:42:33,102 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'RAL1122-PE-н/о-н/о', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': [], 'reason': [], 'basis': 'PE', 'catalog': 'RAL', 'code': '1122', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'panels': '', 'powder': '', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 10:42:33,102 DEBUG ************************
2020-05-04 10:42:33,102 DEBUG soloviev@stardustpaints.ru
2020-05-04 10:42:33,103 DEBUG 33Kgtsl11
2020-05-04 10:42:33,103 DEBUG ************************
2020-05-04 14:29:43,998 DEBUG request:
2020-05-04 14:29:43,998 DEBUG application/json; charset=UTF-8
2020-05-04 14:29:43,999 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-EP-80/100%-гл', 'product': 'Краска', 'delivery_date': '2020-02-28', 'delivery_terms': 'Не определено', 'potential_vol': '8', 'kp_price': '2', 'vol': '2', 'price': '1', 'basis': 'EP', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'surface_thin': '', 'surface_type': [], 'comment': 'kjhkj', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 14:29:43,999 DEBUG ************************
2020-05-04 14:29:43,999 DEBUG soloviev@stardustpaints.ru
2020-05-04 14:29:43,999 DEBUG 33Kgtsl11
2020-05-04 14:29:43,999 DEBUG ************************
2020-05-04 14:29:49,704 DEBUG request:
2020-05-04 14:29:49,704 DEBUG application/json; charset=UTF-8
2020-05-04 14:29:49,704 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'н/оеуые-EP-80/100%-гл', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': 'Не определено', 'reason': 'Не определено', 'basis': 'EP', 'catalog': 'Не определено', 'code': 'еуые', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Не определено', 'postforming': 'Не определено', 'applying': 'Не определено', 'panels': '1', 'powder': '12', 'surface_thin': '', 'surface_type': [], 'comment': 'sdfsd', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 14:29:49,704 DEBUG ************************
2020-05-04 14:29:49,704 DEBUG soloviev@stardustpaints.ru
2020-05-04 14:29:49,704 DEBUG 33Kgtsl11
2020-05-04 14:29:49,704 DEBUG ************************
2020-05-04 14:30:38,645 DEBUG request:
2020-05-04 14:30:38,646 DEBUG application/json; charset=UTF-8
2020-05-04 14:30:38,646 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-EP-80/100%-гл', 'product': 'Краска', 'delivery_date': '2020-02-28', 'delivery_terms': 'Не определено', 'potential_vol': '8', 'kp_price': '2', 'vol': '2', 'price': '1', 'basis': 'EP', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'surface_thin': '', 'surface_type': [], 'comment': 'kjhkj', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 14:30:38,646 DEBUG ************************
2020-05-04 14:30:38,646 DEBUG soloviev@stardustpaints.ru
2020-05-04 14:30:38,647 DEBUG 33Kgtsl11
2020-05-04 14:30:38,647 DEBUG ************************
2020-05-04 14:38:52,880 DEBUG request:
2020-05-04 14:38:52,880 DEBUG application/json; charset=UTF-8
2020-05-04 14:38:52,881 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'н/оеуые-EP-80/100%-гл', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': 'Не определено', 'reason': 'Не определено', 'basis': 'EP', 'catalog': 'Не определено', 'code': 'еуые', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Не определено', 'postforming': 'Не определено', 'applying': 'Не определено', 'panels': '1', 'powder': '12', 'surface_thin': '', 'surface_type': [], 'comment': 'sdfsd', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 14:38:52,882 DEBUG ************************
2020-05-04 14:38:52,882 DEBUG soloviev@stardustpaints.ru
2020-05-04 14:38:52,882 DEBUG 33Kgtsl11
2020-05-04 14:38:52,882 DEBUG ************************
2020-05-04 14:38:56,561 DEBUG request:
2020-05-04 14:38:56,561 DEBUG application/json; charset=UTF-8
2020-05-04 14:38:56,562 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-EP-80/100%-гл', 'product': 'Краска', 'delivery_date': '2020-02-28', 'delivery_terms': 'Не определено', 'potential_vol': '8', 'kp_price': '2', 'vol': '2', 'price': '1', 'basis': 'EP', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'surface_thin': '', 'surface_type': [], 'comment': 'kjhkj', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 14:38:56,562 DEBUG ************************
2020-05-04 14:38:56,562 DEBUG soloviev@stardustpaints.ru
2020-05-04 14:38:56,562 DEBUG 33Kgtsl11
2020-05-04 14:38:56,562 DEBUG ************************
2020-05-04 15:04:42,738 DEBUG request:
2020-05-04 15:04:42,739 DEBUG application/json; charset=UTF-8
2020-05-04 15:04:42,739 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL89898-PE-н/о-н/о', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': 'Не определено', 'potential_vol': '', 'kp_price': '', 'vol': '', 'price': '', 'basis': 'PE', 'catalog': 'RAL', 'code': '89898', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 15:04:42,739 DEBUG ************************
2020-05-04 15:04:42,739 DEBUG soloviev@stardustpaints.ru
2020-05-04 15:04:42,740 DEBUG 33Kgtsl11
2020-05-04 15:04:42,740 DEBUG ************************
2020-05-04 15:13:48,489 DEBUG request:
2020-05-04 15:13:48,489 DEBUG application/json; charset=UTF-8
2020-05-04 15:13:48,490 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': [], 'name': 'RAL3121-PE-н/о-н/о', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': [], 'reason': [], 'basis': 'PE', 'catalog': 'RAL', 'code': '3121', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': [], 'postforming': [], 'applying': [], 'panels': '', 'powder': '', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 15:13:48,490 DEBUG ************************
2020-05-04 15:13:48,490 DEBUG soloviev@stardustpaints.ru
2020-05-04 15:13:48,490 DEBUG 33Kgtsl11
2020-05-04 15:13:48,490 DEBUG ************************
2020-05-04 16:47:30,003 DEBUG request:
2020-05-04 16:47:30,003 DEBUG application/json; charset=UTF-8
2020-05-04 16:47:30,004 DEBUG {'state': 'send_prod', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1018-EP-80/100%-гл', 'product': 'Краска', 'delivery_date': '2020-02-28', 'delivery_terms': 'Не определено', 'potential_vol': '8', 'kp_price': '2', 'vol': '2', 'price': '1', 'basis': 'EP', 'catalog': 'RAL', 'code': '1018', 'shine': 'Глянцевая 80-100%', 'facture': 'Гладкая', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'surface_thin': '', 'surface_type': [], 'comment': 'kjhkj', 'metallic': 1, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 16:47:30,004 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,004 DEBUG paint
2020-05-04 16:47:30,004 DEBUG ['paint']
2020-05-04 16:47:30,004 DEBUG ------------------------
2020-05-04 16:47:30,004 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,004 DEBUG RAL1018-EP-80/100%-гл
2020-05-04 16:47:30,004 DEBUG ['RAL1018-EP-80/100%-гл']
2020-05-04 16:47:30,004 DEBUG ------------------------
2020-05-04 16:47:30,004 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,004 DEBUG Краска
2020-05-04 16:47:30,004 DEBUG ['Краска']
2020-05-04 16:47:30,004 DEBUG ------------------------
2020-05-04 16:47:30,004 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,004 DEBUG 2020-02-28
2020-05-04 16:47:30,005 DEBUG ['2020-02-28']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,005 DEBUG Не определено
2020-05-04 16:47:30,005 DEBUG ['Не определено']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,005 DEBUG 8
2020-05-04 16:47:30,005 DEBUG ['8']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,005 DEBUG 2
2020-05-04 16:47:30,005 DEBUG ['2']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,005 DEBUG 2
2020-05-04 16:47:30,005 DEBUG ['2']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,005 DEBUG 1
2020-05-04 16:47:30,005 DEBUG ['1']
2020-05-04 16:47:30,005 DEBUG ------------------------
2020-05-04 16:47:30,005 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG EP
2020-05-04 16:47:30,006 DEBUG ['EP']
2020-05-04 16:47:30,006 DEBUG ------------------------
2020-05-04 16:47:30,006 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG RAL
2020-05-04 16:47:30,006 DEBUG ['RAL']
2020-05-04 16:47:30,006 DEBUG ------------------------
2020-05-04 16:47:30,006 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG 1018
2020-05-04 16:47:30,006 DEBUG ['1018']
2020-05-04 16:47:30,006 DEBUG ------------------------
2020-05-04 16:47:30,006 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG Глянцевая 80-100%
2020-05-04 16:47:30,006 DEBUG ['Глянцевая 80-100%']
2020-05-04 16:47:30,006 DEBUG ------------------------
2020-05-04 16:47:30,006 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG Гладкая
2020-05-04 16:47:30,006 DEBUG ['Гладкая']
2020-05-04 16:47:30,006 DEBUG ------------------------
2020-05-04 16:47:30,006 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,006 DEBUG Стандарт
2020-05-04 16:47:30,006 DEBUG ['Стандарт']
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG T0
2020-05-04 16:47:30,007 DEBUG ['T0']
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG Внешнее
2020-05-04 16:47:30,007 DEBUG ['Внешнее']
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG 
2020-05-04 16:47:30,007 DEBUG ['']
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG []
2020-05-04 16:47:30,007 DEBUG [[]]
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG kjhkj
2020-05-04 16:47:30,007 DEBUG ['kjhkj']
2020-05-04 16:47:30,007 DEBUG ------------------------
2020-05-04 16:47:30,007 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,007 DEBUG 1
2020-05-04 16:47:30,008 DEBUG [1]
2020-05-04 16:47:30,008 DEBUG ------------------------
2020-05-04 16:47:30,008 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,008 DEBUG 0
2020-05-04 16:47:30,008 DEBUG [0]
2020-05-04 16:47:30,008 DEBUG ------------------------
2020-05-04 16:47:30,008 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,008 DEBUG 0
2020-05-04 16:47:30,008 DEBUG [0]
2020-05-04 16:47:30,008 DEBUG ------------------------
2020-05-04 16:47:30,008 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,008 DEBUG 0
2020-05-04 16:47:30,008 DEBUG [0]
2020-05-04 16:47:30,008 DEBUG ------------------------
2020-05-04 16:47:30,008 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,008 DEBUG 0
2020-05-04 16:47:30,008 DEBUG [0]
2020-05-04 16:47:30,008 DEBUG ------------------------
2020-05-04 16:47:30,008 DEBUG ++++++++++++++++++++++++
2020-05-04 16:47:30,008 DEBUG 0
2020-05-04 16:47:30,008 DEBUG [0]
2020-05-04 16:47:30,009 DEBUG ------------------------
2020-05-04 19:02:31,327 DEBUG request:
2020-05-04 19:02:31,328 DEBUG application/json; charset=UTF-8
2020-05-04 19:02:31,329 DEBUG {'state': 'set_score', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'paint', 'name': 'RAL1015-EP-Полуглянцевая 55-80%-шгр', 'product': 'Краска', 'delivery_date': '', 'delivery_terms': [], 'potential_vol': '25', 'kp_price': '100', 'vol': '1', 'price': '90', 'basis': 'EP', 'catalog': 'RAL', 'code': '1015', 'shine': 'Полуглянцевая 55-80%', 'facture': 'Шагрень', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 1, 'chameleon': 0, 'antibacterial': 1, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 19:45:04,097 DEBUG request:
2020-05-04 19:45:04,097 DEBUG application/json; charset=UTF-8
2020-05-04 19:45:04,098 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'RAL1015-EP-Полуглянцевая 55-80%-шгр', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': [], 'reason': [], 'basis': 'EP', 'catalog': 'RAL', 'code': '1015', 'shine': 'Полуглянцевая 55-80%', 'facture': 'Шагрень', 'temperature': 'Стандарт', 'postforming': 'T0', 'applying': 'Внешнее', 'panels': '', 'powder': '', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 1, 'chameleon': 0, 'antibacterial': 1, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 19:45:04,098 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,098 DEBUG sample
2020-05-04 19:45:04,098 DEBUG ['sample']
2020-05-04 19:45:04,098 DEBUG ------------------------
2020-05-04 19:45:04,098 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,098 DEBUG RAL1015-EP-Полуглянцевая 55-80%-шгр
2020-05-04 19:45:04,098 DEBUG ['RAL1015-EP-Полуглянцевая 55-80%-шгр']
2020-05-04 19:45:04,098 DEBUG ------------------------
2020-05-04 19:45:04,098 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,098 DEBUG Краска
2020-05-04 19:45:04,098 DEBUG ['Краска']
2020-05-04 19:45:04,098 DEBUG ------------------------
2020-05-04 19:45:04,098 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,098 DEBUG 
2020-05-04 19:45:04,098 DEBUG ['']
2020-05-04 19:45:04,098 DEBUG ------------------------
2020-05-04 19:45:04,098 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,098 DEBUG 
2020-05-04 19:45:04,099 DEBUG ['']
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,099 DEBUG []
2020-05-04 19:45:04,099 DEBUG [[]]
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,099 DEBUG []
2020-05-04 19:45:04,099 DEBUG [[]]
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,099 DEBUG EP
2020-05-04 19:45:04,099 DEBUG ['EP']
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,099 DEBUG RAL
2020-05-04 19:45:04,099 DEBUG ['RAL']
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,099 DEBUG 1015
2020-05-04 19:45:04,099 DEBUG ['1015']
2020-05-04 19:45:04,099 DEBUG ------------------------
2020-05-04 19:45:04,099 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG Полуглянцевая 55-80%
2020-05-04 19:45:04,100 DEBUG ['Полуглянцевая 55-80%']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,100 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG Шагрень
2020-05-04 19:45:04,100 DEBUG ['Шагрень']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,100 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG Стандарт
2020-05-04 19:45:04,100 DEBUG ['Стандарт']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,100 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG T0
2020-05-04 19:45:04,100 DEBUG ['T0']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,100 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG Внешнее
2020-05-04 19:45:04,100 DEBUG ['Внешнее']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,100 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,100 DEBUG 
2020-05-04 19:45:04,100 DEBUG ['']
2020-05-04 19:45:04,100 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG 
2020-05-04 19:45:04,101 DEBUG ['']
2020-05-04 19:45:04,101 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG 
2020-05-04 19:45:04,101 DEBUG ['']
2020-05-04 19:45:04,101 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG []
2020-05-04 19:45:04,101 DEBUG [[]]
2020-05-04 19:45:04,101 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG 
2020-05-04 19:45:04,101 DEBUG ['']
2020-05-04 19:45:04,101 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG 1
2020-05-04 19:45:04,101 DEBUG [1]
2020-05-04 19:45:04,101 DEBUG ------------------------
2020-05-04 19:45:04,101 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,101 DEBUG 0
2020-05-04 19:45:04,101 DEBUG [0]
2020-05-04 19:45:04,102 DEBUG ------------------------
2020-05-04 19:45:04,102 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,102 DEBUG 1
2020-05-04 19:45:04,102 DEBUG [1]
2020-05-04 19:45:04,102 DEBUG ------------------------
2020-05-04 19:45:04,102 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,102 DEBUG 0
2020-05-04 19:45:04,102 DEBUG [0]
2020-05-04 19:45:04,102 DEBUG ------------------------
2020-05-04 19:45:04,102 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,102 DEBUG 0
2020-05-04 19:45:04,102 DEBUG [0]
2020-05-04 19:45:04,102 DEBUG ------------------------
2020-05-04 19:45:04,102 DEBUG ++++++++++++++++++++++++
2020-05-04 19:45:04,102 DEBUG 0
2020-05-04 19:45:04,102 DEBUG [0]
2020-05-04 19:45:04,102 DEBUG ------------------------
2020-05-04 19:52:45,544 DEBUG request:
2020-05-04 19:52:45,544 DEBUG application/json; charset=UTF-8
2020-05-04 19:52:45,544 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'RAL32323-PE-н/о-н/о', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': [], 'reason': [], 'basis': 'PE', 'catalog': 'RAL', 'code': '32323', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'panels': '', 'powder': '', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 19:52:45,544 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,544 DEBUG sample
2020-05-04 19:52:45,544 DEBUG ['sample']
2020-05-04 19:52:45,544 DEBUG ------------------------
2020-05-04 19:52:45,544 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,544 DEBUG RAL32323-PE-н/о-н/о
2020-05-04 19:52:45,545 DEBUG ['RAL32323-PE-н/о-н/о']
2020-05-04 19:52:45,545 DEBUG ------------------------
2020-05-04 19:52:45,545 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,545 DEBUG Краска
2020-05-04 19:52:45,545 DEBUG ['Краска']
2020-05-04 19:52:45,545 DEBUG ------------------------
2020-05-04 19:52:45,545 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,545 DEBUG 
2020-05-04 19:52:45,545 DEBUG ['']
2020-05-04 19:52:45,545 DEBUG ------------------------
2020-05-04 19:52:45,545 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,545 DEBUG 
2020-05-04 19:52:45,545 DEBUG ['']
2020-05-04 19:52:45,545 DEBUG ------------------------
2020-05-04 19:52:45,545 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,545 DEBUG []
2020-05-04 19:52:45,545 DEBUG [[]]
2020-05-04 19:52:45,545 DEBUG ------------------------
2020-05-04 19:52:45,545 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,545 DEBUG []
2020-05-04 19:52:45,546 DEBUG [[]]
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,546 DEBUG PE
2020-05-04 19:52:45,546 DEBUG ['PE']
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,546 DEBUG RAL
2020-05-04 19:52:45,546 DEBUG ['RAL']
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,546 DEBUG 32323
2020-05-04 19:52:45,546 DEBUG ['32323']
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,546 DEBUG Не определено
2020-05-04 19:52:45,546 DEBUG ['Не определено']
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,546 DEBUG Не определено
2020-05-04 19:52:45,546 DEBUG ['Не определено']
2020-05-04 19:52:45,546 DEBUG ------------------------
2020-05-04 19:52:45,546 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG Не определено
2020-05-04 19:52:45,547 DEBUG ['Не определено']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,547 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG Нет
2020-05-04 19:52:45,547 DEBUG ['Нет']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,547 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG Внутренее
2020-05-04 19:52:45,547 DEBUG ['Внутренее']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,547 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG 
2020-05-04 19:52:45,547 DEBUG ['']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,547 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG 
2020-05-04 19:52:45,547 DEBUG ['']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,547 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,547 DEBUG 
2020-05-04 19:52:45,547 DEBUG ['']
2020-05-04 19:52:45,547 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG []
2020-05-04 19:52:45,548 DEBUG [[]]
2020-05-04 19:52:45,548 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG 
2020-05-04 19:52:45,548 DEBUG ['']
2020-05-04 19:52:45,548 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG 0
2020-05-04 19:52:45,548 DEBUG [0]
2020-05-04 19:52:45,548 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG 0
2020-05-04 19:52:45,548 DEBUG [0]
2020-05-04 19:52:45,548 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG 0
2020-05-04 19:52:45,548 DEBUG [0]
2020-05-04 19:52:45,548 DEBUG ------------------------
2020-05-04 19:52:45,548 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,548 DEBUG 0
2020-05-04 19:52:45,549 DEBUG [0]
2020-05-04 19:52:45,549 DEBUG ------------------------
2020-05-04 19:52:45,549 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,549 DEBUG 0
2020-05-04 19:52:45,549 DEBUG [0]
2020-05-04 19:52:45,549 DEBUG ------------------------
2020-05-04 19:52:45,549 DEBUG ++++++++++++++++++++++++
2020-05-04 19:52:45,549 DEBUG 0
2020-05-04 19:52:45,549 DEBUG [0]
2020-05-04 19:52:45,549 DEBUG ------------------------
2020-05-04 19:53:06,210 DEBUG request:
2020-05-04 19:53:06,211 DEBUG application/json; charset=UTF-8
2020-05-04 19:53:06,211 DEBUG {'state': 'send_lab', 'manager_mail': 'c29sb3ZpZXZAc3RhcmR1c3RwYWludHMucnU=', 'manager_mail_pass': 'MzNLZ3RzbDEx', 'sample_data': {'product_type': 'sample', 'name': 'RAL123213-PE-н/о-н/о', 'product': 'Краска', 'client_sample': '', 'ntime_applying': '', 'status': [], 'reason': [], 'basis': 'PE', 'catalog': 'RAL', 'code': '123213', 'shine': 'Не определено', 'facture': 'Не определено', 'temperature': 'Не определено', 'postforming': 'Нет', 'applying': 'Внутренее', 'panels': '', 'powder': '', 'surface_thin': '', 'surface_type': [], 'comment': '', 'metallic': 0, 'chameleon': 0, 'antibacterial': 0, 'antigraffiti': 0, 'architect': 0, 'zinc': 0}}
2020-05-04 19:53:06,211 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,212 DEBUG sample
2020-05-04 19:53:06,212 DEBUG ['sample']
2020-05-04 19:53:06,212 DEBUG ------------------------
2020-05-04 19:53:06,212 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,212 DEBUG RAL123213-PE-н/о-н/о
2020-05-04 19:53:06,213 DEBUG ['RAL123213-PE-н/о-н/о']
2020-05-04 19:53:06,213 DEBUG ------------------------
2020-05-04 19:53:06,213 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,213 DEBUG Краска
2020-05-04 19:53:06,213 DEBUG ['Краска']
2020-05-04 19:53:06,213 DEBUG ------------------------
2020-05-04 19:53:06,213 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,214 DEBUG 
2020-05-04 19:53:06,214 DEBUG ['']
2020-05-04 19:53:06,214 DEBUG ------------------------
2020-05-04 19:53:06,214 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,214 DEBUG 
2020-05-04 19:53:06,214 DEBUG ['']
2020-05-04 19:53:06,214 DEBUG ------------------------
2020-05-04 19:53:06,214 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,215 DEBUG []
2020-05-04 19:53:06,215 DEBUG [[]]
2020-05-04 19:53:06,215 DEBUG ------------------------
2020-05-04 19:53:06,215 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,215 DEBUG []
2020-05-04 19:53:06,215 DEBUG [[]]
2020-05-04 19:53:06,215 DEBUG ------------------------
2020-05-04 19:53:06,215 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,216 DEBUG PE
2020-05-04 19:53:06,216 DEBUG ['PE']
2020-05-04 19:53:06,216 DEBUG ------------------------
2020-05-04 19:53:06,216 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,216 DEBUG RAL
2020-05-04 19:53:06,216 DEBUG ['RAL']
2020-05-04 19:53:06,216 DEBUG ------------------------
2020-05-04 19:53:06,217 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,217 DEBUG 123213
2020-05-04 19:53:06,217 DEBUG ['123213']
2020-05-04 19:53:06,217 DEBUG ------------------------
2020-05-04 19:53:06,217 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,217 DEBUG Не определено
2020-05-04 19:53:06,217 DEBUG ['Не определено']
2020-05-04 19:53:06,217 DEBUG ------------------------
2020-05-04 19:53:06,218 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,218 DEBUG Не определено
2020-05-04 19:53:06,218 DEBUG ['Не определено']
2020-05-04 19:53:06,218 DEBUG ------------------------
2020-05-04 19:53:06,218 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,218 DEBUG Не определено
2020-05-04 19:53:06,218 DEBUG ['Не определено']
2020-05-04 19:53:06,218 DEBUG ------------------------
2020-05-04 19:53:06,219 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,219 DEBUG Нет
2020-05-04 19:53:06,219 DEBUG ['Нет']
2020-05-04 19:53:06,219 DEBUG ------------------------
2020-05-04 19:53:06,219 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,219 DEBUG Внутренее
2020-05-04 19:53:06,219 DEBUG ['Внутренее']
2020-05-04 19:53:06,219 DEBUG ------------------------
2020-05-04 19:53:06,220 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,220 DEBUG 
2020-05-04 19:53:06,220 DEBUG ['']
2020-05-04 19:53:06,220 DEBUG ------------------------
2020-05-04 19:53:06,220 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,220 DEBUG 
2020-05-04 19:53:06,220 DEBUG ['']
2020-05-04 19:53:06,221 DEBUG ------------------------
2020-05-04 19:53:06,221 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,221 DEBUG 
2020-05-04 19:53:06,221 DEBUG ['']
2020-05-04 19:53:06,221 DEBUG ------------------------
2020-05-04 19:53:06,221 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,221 DEBUG []
2020-05-04 19:53:06,221 DEBUG [[]]
2020-05-04 19:53:06,222 DEBUG ------------------------
2020-05-04 19:53:06,222 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,222 DEBUG 
2020-05-04 19:53:06,222 DEBUG ['']
2020-05-04 19:53:06,222 DEBUG ------------------------
2020-05-04 19:53:06,222 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,222 DEBUG 0
2020-05-04 19:53:06,222 DEBUG [0]
2020-05-04 19:53:06,223 DEBUG ------------------------
2020-05-04 19:53:06,223 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,223 DEBUG 0
2020-05-04 19:53:06,223 DEBUG [0]
2020-05-04 19:53:06,223 DEBUG ------------------------
2020-05-04 19:53:06,223 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,223 DEBUG 0
2020-05-04 19:53:06,223 DEBUG [0]
2020-05-04 19:53:06,223 DEBUG ------------------------
2020-05-04 19:53:06,223 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,223 DEBUG 0
2020-05-04 19:53:06,224 DEBUG [0]
2020-05-04 19:53:06,224 DEBUG ------------------------
2020-05-04 19:53:06,224 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,224 DEBUG 0
2020-05-04 19:53:06,224 DEBUG [0]
2020-05-04 19:53:06,224 DEBUG ------------------------
2020-05-04 19:53:06,224 DEBUG ++++++++++++++++++++++++
2020-05-04 19:53:06,224 DEBUG 0
2020-05-04 19:53:06,224 DEBUG [0]
2020-05-04 19:53:06,224 DEBUG ------------------------
2020-05-06 14:37:25,432 DEBUG Using selector: EpollSelector
2020-05-06 14:47:00,166 DEBUG Using selector: EpollSelector
2020-05-06 14:49:34,868 DEBUG Using selector: EpollSelector
2020-05-06 16:41:26,812 ERROR Internal Server Error: /amoapi/api/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 75, in api
    if not api_key == request['api_key']:
TypeError: 'Request' object is not subscriptable
2020-05-06 16:44:10,492 DEBUG Using selector: EpollSelector
2020-05-06 16:46:32,769 DEBUG Using selector: EpollSelector
2020-05-06 22:17:55,668 DEBUG Using selector: EpollSelector
2020-05-06 22:26:48,869 DEBUG Using selector: EpollSelector
2020-05-06 22:41:31,955 DEBUG Using selector: EpollSelector
2020-05-06 22:42:26,673 DEBUG Using selector: EpollSelector
2020-05-06 22:46:31,777 DEBUG Using selector: EpollSelector
2020-05-06 22:46:31,819 ERROR Internal Server Error: /amoapi/api/
Traceback (most recent call last):
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/perespimka/monyze/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/perespimka/monyze/amoapi/views.py", line 92, in api
    sum_ += pl.price * pl.vol
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
2020-05-06 22:48:38,798 DEBUG Using selector: EpollSelector
2020-05-06 23:20:12,793 DEBUG Using selector: EpollSelector
2020-05-06 23:20:24,284 DEBUG Using selector: EpollSelector
2020-05-07 10:18:57,788 DEBUG Using selector: EpollSelector
